apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netdevops-ingress
spec:
  rules:
    - host: netdevops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netdevops-app
                port:
                  number: 80
