global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: "celery_worker"
    static_configs:
      - targets: ["worker:9091"]
