apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netdevops-db
  namespace: netdevops-staging
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: netdevops-secretstore
    kind: SecretStore
  target:
    name: netdevops-db
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: netdevops-db-source
        property: DATABASE_URL
