apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: netdevops-secretstore
  namespace: netdevops-staging
spec:
  provider:
    kubernetes:
      remoteNamespace: netdevops-staging
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: netdevops-api
