apiVersion: v1
kind: Service
metadata:
  name: {{ include "netdevops.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
