{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netdevops.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: api
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "netdevops.fullname" . }}-api
                port:
                  number: 8000
{{- end }}
