apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "netdevops.fullname" . }}-worker-pdb
  labels:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: worker
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netdevops.name" . }}
      app.kubernetes.io/component: worker
