apiVersion: v1
kind: Secret
metadata:
  name: netdevops-secrets
  namespace: netdevops
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.secrets.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.POSTGRES_PASSWORD }}"
  POSTGRES_DB: "{{ .Values.secrets.POSTGRES_DB }}"
  SECRET_KEY: "{{ .Values.secrets.SECRET_KEY }}"
  VAULT_URL: "{{ .Values.secrets.VAULT_URL }}"
  VAULT_TOKEN: "{{ .Values.secrets.VAULT_TOKEN }}"
