{{- if .Values.postgres.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netdevops.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "netdevops.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "netdevops.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netdevops.name" . }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "netdevops.name" . }}
        app.kubernetes.io/component: postgres
    spec:
      serviceAccountName: netdevops-postgres
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          envFrom:
            - secretRef:
                name: {{ include "netdevops.fullname" . }}-db
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}

{{- end }}
