apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdevops-worker
  namespace: netdevops
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: netdevops-worker
  template:
    metadata:
      labels:
        app: netdevops-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args: ["-A", "app.worker.celery_app.app", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: netdevops-config
            - secretRef:
                name: netdevops-secrets
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
