apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netdevops.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "netdevops.name" . }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netdevops.name" . }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "netdevops.name" . }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: netdevops-worker
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: {{ toYaml .Values.worker.command | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
