apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdevops-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdevops-worker
  template:
    metadata:
      labels:
        app: netdevops-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/YOUR-USERNAME/netdevops-app:latest
          command: ["celery", "-A", "app.worker.celery_app.app", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: netdevops-config
            - secretRef:
                name: netdevops-secret
