apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdevops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netdevops-app
  template:
    metadata:
      labels:
        app: netdevops-app
    spec:
      containers:
        - name: app
          image: ghcr.io/YOUR-USERNAME/netdevops-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: netdevops-config
            - secretRef:
                name: netdevops-secret
---
apiVersion: v1
kind: Service
metadata:
  name: netdevops-app
spec:
  type: ClusterIP
  selector:
    app: netdevops-app
  ports:
    - port: 8000
      targetPort: 8000
