apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdevops-app
  namespace: netdevops
spec:
  replicas: {{ .Values.replicaCount.app }}
  selector:
    matchLabels:
      app: netdevops-app
  template:
    metadata:
      labels:
        app: netdevops-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: netdevops-config
            - secretRef:
                name: netdevops-secrets
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.app | nindent 12 }}
