apiVersion: v1
kind: ConfigMap
metadata:
  name: netdevops-app-config
data:
  APP_ENV: "dev"
  DATABASE_URL: "postgresql+psycopg2://netdevops_user:netdevops_pass@postgres:5432/netdevops_db"
  REDIS_URL: "redis://redis:6379/0"
